defaults:
  - dataset: re10k
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - override dataset/view_sampler: all

dataset:
  overfit_to_scene: null

data_loader:
  train:
    num_workers: 0
    persistent_workers: true
    batch_size: 1
    seed: 1234
  test:
    num_workers: 8
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 0
    persistent_workers: true
    batch_size: 1
    seed: 3456

index_generator:
  num_target_views: 49
  min_overlap: 0.05
  max_overlap: 0.25
  min_distance: 1
  max_distance: 1
  output_path: noposplat/assets/evaluation_index_acid
  save_previews: false
  seed: 42

seed: 456
