defaults:
  - base_dataset
  # - view_sampler: bounded
  - view_sampler: arbitrary
  - optional view_sampler_dataset_specific_config@view_sampler: bounded_re10k

name: re10k
roots: [/home/xshen/xshen_shortcut/re10k] # for M3
# roots: [/home/xshen/xshen_shortcut/acid] # for M3
# roots: [/home/max/dl_coding_2404/re10k] # for local

input_image_shape: [256, 256]
# input_image_shape: [256, 455] # for svc
# input_image_shape: [256, 448] # for mvsplat360
original_image_shape: [360, 640]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e10
max_fov: 100.0
