name: bounded

num_target_views: 12
num_context_views: 2

min_distance_between_context_views: 12
max_distance_between_context_views: 12
min_distance_to_context_views: 1

warm_up_steps: 0
initial_min_distance_between_context_views: 48
initial_max_distance_between_context_views: 60